export const systemConfig = {
  timePeriod: 60, // Ex: timePeriod: 60 (in minutes)
  cronInterval: 50, //Ex: cronInterval: 50 (in minutes)
  filesPerPage: 200, // Ex: filesPerPage: 200
  excludedAssistants: [
    "HUB",
    "GTAE",
    "testes GEF",
    "testes GEP",
    "testes Suporte",
  ],
  sensitiveFields: [
    "resultUsuario",
    "resultAluno",
    "cpf",
    "nome",
    "email",
    "dataNascimento",
    "nomeSobrenome",
    "contrato",
    "private",
    "resultDebitos",
    "resultBoleto",
    "resultValoresPagos",
    "resultDeclaracaoMatricula",
    "resultArquivoMatricula",
    "resultCertificados",
    "resultArquivoCertificado",
    "resultViaNF",
    "resultEnvioEmail",
    "cursoEscolhido",
    "docCliente",
    "unidade",
    "codigoPessoaCorp",
    "codigoLoginUnico",
    "loginEdu",
    "resultCancelamento",
    "resultAnulacao",
    "resultReversao",
    "resultConciliacao",
    "resultProrrogacao",
    "resultDescontoIsencao",
    "resultNaoProcessados",
    "resultMatriculaPorData",
    "cpfCnpj",
    "dadosBancarios",
    "nomePrestador",
    "CpfPrestador",
    "pisPasepNit",
    "banco",
    "agencia",
    "numeroConta",
  ],
};
